#!/usr/bin/env node
/**
 * Moves real secrets out of .env.example and into .env.local, then resets
 * .env.example back to an empty template.
 *
 * .env.example is a template that gets shared, screenshotted, and pasted into
 * issues. Real keys do not belong in it even for a minute. .env.local is the file
 * git ignores and nobody circulates.
 *
 * Prints key names and value lengths only, never the values themselves, so running
 * it in a shared terminal or a transcript does not leak what it just secured.
 *
 *   node scripts/secure-env.mjs
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const EXAMPLE = ".env.example";
const LOCAL = ".env.local";

if (!existsSync(EXAMPLE)) {
  console.error(`No ${EXAMPLE} found.`);
  process.exit(1);
}

const raw = readFileSync(EXAMPLE, "utf8");
const lines = raw.split("\n");

/** Values that are obviously placeholders, not secrets worth moving. */
const PLACEHOLDER = /^(|http:\/\/localhost:3000|your[-_].*|xxx+|<.*>|changeme|todo)$/i;

const moved = [];
const cleaned = lines.map((line) => {
  const t = line.trim();
  if (!t || t.startsWith("#") || !t.includes("=")) return line;

  const idx = line.indexOf("=");
  const key = line.slice(0, idx).trim();
  const value = line.slice(idx + 1).trim();

  if (PLACEHOLDER.test(value)) return line;

  moved.push([key, value]);
  return `${key}=`;
});

if (moved.length === 0) {
  console.log(`Nothing to move. Every key in ${EXAMPLE} is already empty or a placeholder.`);
  console.log("If you just pasted values in your editor, save the file first.");
  process.exit(0);
}

// Merge into .env.local, letting the newly moved values win.
const existing = new Map();
if (existsSync(LOCAL)) {
  for (const line of readFileSync(LOCAL, "utf8").split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#") || !t.includes("=")) continue;
    const i = line.indexOf("=");
    existing.set(line.slice(0, i).trim(), line.slice(i + 1).trim());
  }
}
for (const [k, v] of moved) existing.set(k, v);

const out = [
  "# socialX portal :: local secrets",
  "# Generated by scripts/secure-env.mjs. Git ignored. Do not share or paste this file.",
  "",
  ...[...existing.entries()].map(([k, v]) => `${k}=${v}`),
  "",
].join("\n");

writeFileSync(LOCAL, out, { mode: 0o600 });
writeFileSync(EXAMPLE, cleaned.join("\n"));

console.log(`Moved ${moved.length} value(s) into ${LOCAL} (chmod 600) and cleared them from ${EXAMPLE}:`);
for (const [k, v] of moved) console.log(`  ${k}  [${v.length} chars]`);
console.log(`\n${LOCAL} now holds ${existing.size} key(s). Values were never printed.`);
